### ISSUE TITLE
edm displays not right

### ISSUE THREAD

**Issue by MarkRivers** [areaDetector/aravisGigE#38]
I am trying to run edm to display the autogenerated edm displays for my camera.

This is a screen shot of the main screen.  the aravisCamera.edl included screen is displaying completed frames, but does not fit well.  The ADBase.edl is probably not working because ADBase.edl can be both from autoconvert and from an old ADBase.edl which is very different from ADBase.adl?  ADBase.adl is not intended to be embedded, it is a standalone top-level screen.  The Related display button at the bottom does not have any label.  Any idea why not?
![image](https://user-images.githubusercontent.com/6115534/42237973-007342b2-7ec5-11e8-9a36-259b4f39b7fc.png)

If i click on the related display button to get the features this is what I see.  Only the Gain seems to be connected.  As I move the mouse the I get pop-up windows saying their are unsaved changes, do I want to exit.  But I did nothing to ask to exit?

![image](https://user-images.githubusercontent.com/6115534/42238075-52ab5920-7ec5-11e8-8ed4-3ba62625cf18.png)

**Comment by bhill-slac** [comment]
Which version of aravisGigE are you running?   I think a number of these issues were fixed when some of my pull requests were merged to master after the R2-1 release.
Re the white controls, those PVs might be UDF due to PINI=NO.   I prefer to show UDF in purple, color 45, rather than white, color 0.   That's determined by your alarm colors which is configured at the end of $EDMOBJECTS/colors.list.
alarm {
  disconnected : "White-Disconn-0"
  invalid      : "Invalid-45"
  minor        : "Monitor: MINOR"
  major        : "Monitor: MAJOR"
  noalarm      : *
 }
Cheers, Bruce

**Comment by MarkRivers** [comment]
I am running from the master branch, and I am up to date with Github.
I'll look into the colors.  But now that I have an medm generator running I am less worried about the edm displays.

Thanks.

**Comment by MarkRivers** [comment]
I am closing this since I now have an medm solution and am not familiar with edm.
